var wikiContents = [
    {
        "Index" : 0,
        "Id":"0000000000",
        "Parent" : "wikiContents",
        "Category": "lastReviews",
        "Segment": "Undefined",
        "Title":"Úlimas Atualizações",
        "Description": "Tela das últimas atualizações",
        "Keys" : [],
        "Link" : [],
        "Hashtags" : [],
        "DateUpload": "08/08/2020",
        "Body": getLastReviewsList,
        "Active":true,
        "IsDBContent":false,
        "Author": "c08460"
    },
    {
        "Index": 1,
        "Id":"0000000001",
        "Parent" : "wikiContents",
        "Category" : "Wiki",
        "Segment": "Habitação",
        "Title" : "Pedra do Reino - Prestações pagas pela fiadora/Construtora",
        "Description": "Pedra do Reino - Como entender as prestações pegas pela fiadora/Construtora.",
        "Keys" : [],
        "Link" : [],
        "Hashtags" : ["#pausahabitação", "#pausaemergencial", "#pausafinanciamento", "#pausacovid", "#pausahabitacional", "pausahabitacao"],
        "DateUpload": "08/08/2020",
        "Body" : "<div class='frameMain'><b>Teste 1</b><div><br></div><div>Para ver se tudo está funcionando, vamos fazer assim.</div><div><br></div><div>Para mais informações, consulte o&nbsp;<a href='http://www.google.com' target='_blank'>google</a>.</div><b>Teste 1</b><div><br></div><div>Para ver se tudo está funcionando, vamos fazer assim.</div><div><br></div><div>Para mais informações, consulte o&nbsp;<a href='http://www.google.com' target='_blank'>google</a>.</div><b>Teste 1</b><div><br></div><div>Para ver se tudo está funcionando, vamos fazer assim.</div><div><br></div><div>Para mais informações, consulte o&nbsp;<a href='http://www.google.com' target='_blank'>google</a>.</div><b>Teste 1</b><div><br></div><div>Para ver se tudo está funcionando, vamos fazer assim.</div><div><br></div><div>Para mais informações, consulte o&nbsp;<a href='http://www.google.com' target='_blank'>google</a>.</div><b>Teste 1</b><div><br></div><div>Para ver se tudo está funcionando, vamos fazer assim.</div><div><br></div><div>Para mais informações, consulte o&nbsp;<a href='http://www.google.com' target='_blank'>google</a>.</div><b>Teste 1</b><div><br></div><div>Para ver se tudo está funcionando, vamos fazer assim.</div><div><br></div><div>Para mais informações, consulte o&nbsp;<a href='http://www.google.com' target='_blank'>google</a>.</div><b>Teste 1</b><div><br></div><div>Para ver se tudo está funcionando, vamos fazer assim.</div><div><br></div><div>Para mais informações, consulte o&nbsp;<a href='http://www.google.com' target='_blank'>google</a>.</div><b>Teste 1</b><div><br></div><div>Para ver se tudo está funcionando, vamos fazer assim.</div><div><br></div><div>Para mais informações, consulte o&nbsp;<a href='http://www.google.com' target='_blank'>google</a>.</div><b>Teste 1</b><div><br></div><div>Para ver se tudo está funcionando, vamos fazer assim.</div><div><br></div><div>Para mais informações, consulte o&nbsp;<a href='http://www.google.com' target='_blank'>google</a>.</div><b>Teste 1</b><div><br></div><div>Para ver se tudo está funcionando, vamos fazer assim.</div><div><br></div><div>Para mais informações, consulte o&nbsp;<a href='http://www.google.com' target='_blank'>google</a>.</div><b>Teste 1</b><div><br></div><div>Para ver se tudo está funcionando, vamos fazer assim.</div><div><br></div><div>Para mais informações, consulte o&nbsp;<a href='http://www.google.com' target='_blank'>google</a>.</div><b>Teste 1</b><div><br></div><div>Para ver se tudo está funcionando, vamos fazer assim.</div><div><br></div><div>Para mais informações, consulte o&nbsp;<a href='http://www.google.com' target='_blank'>google</a>.</div><b>Teste 1</b><div><br></div><div>Para ver se tudo está funcionando, vamos fazer assim.</div><div><br></div><div>Para mais informações, consulte o&nbsp;<a href='http://www.google.com' target='_blank'>google</a>.</div><b>Teste 1</b><div><br></div><div>Para ver se tudo está funcionando, vamos fazer assim.</div><div><br></div><div>Para mais informações, consulte o&nbsp;<a href='http://www.google.com' target='_blank'>google</a>.</div><b>Teste 1</b><div><br></div><div>Para ver se tudo está funcionando, vamos fazer assim.</div><div><br></div><div>Para mais informações, consulte o&nbsp;<a href='http://www.google.com' target='_blank'>google</a>.</div><b>Teste 1</b><div><br></div><div>Para ver se tudo está funcionando, vamos fazer assim.</div><div><br></div><div>Para mais informações, consulte o&nbsp;<a href='http://www.google.com' target='_blank'>google</a>.</div><b>Teste 1</b><div><br></div><div>Para ver se tudo está funcionando, vamos fazer assim.</div><div><br></div><div>Para mais informações, consulte o&nbsp;<a href='http://www.google.com' target='_blank'>google</a>.</div><b>Teste 1</b><div><br></div><div>Para ver se tudo está funcionando, vamos fazer assim.</div><div><br></div><div>Para mais informações, consulte o&nbsp;<a href='http://www.google.com' target='_blank'>google</a>.</div><b>Teste 1</b><div><br></div><div>Para ver se tudo está funcionando, vamos fazer assim.</div><div><br></div><div>Para mais informações, consulte o&nbsp;<a href='http://www.google.com' target='_blank'>google</a>.</div><b>Teste 1</b><div><br></div><div>Para ver se tudo está funcionando, vamos fazer assim.</div><div><br></div><div>Para mais informações, consulte o&nbsp;<a href='http://www.google.com' target='_blank'>google</a>.</div><b>Teste 1</b><div><br></div><div>Para ver se tudo está funcionando, vamos fazer assim.</div><div><br></div><div>Para mais informações, consulte o&nbsp;<a href='http://www.google.com' target='_blank'>google</a>.</div><b>Teste 1</b><div><br></div><div>Para ver se tudo está funcionando, vamos fazer assim.</div><div><br></div><div>Para mais informações, consulte o&nbsp;<a href='http://www.google.com' target='_blank'>google</a>.</div><b>Teste 1</b><div><br></div><div>Para ver se tudo está funcionando, vamos fazer assim.</div><div><br></div><div>Para mais informações, consulte o&nbsp;<a href='http://www.google.com' target='_blank'>google</a>.</div><b>Teste 1</b><div><br></div><div>Para ver se tudo está funcionando, vamos fazer assim.</div><div><br></div><div>Para mais informações, consulte o&nbsp;<a href='http://www.google.com' target='_blank'>google</a>.</div><b>Teste 1</b><div><br></div><div>Para ver se tudo está funcionando, vamos fazer assim.</div><div><br></div><div>Para mais informações, consulte o&nbsp;<a href='http://www.google.com' target='_blank'>google</a>.</div><b>Teste 1</b><div><br></div><div>Para ver se tudo está funcionando, vamos fazer assim.</div><div><br></div><div>Para mais informações, consulte o&nbsp;<a href='http://www.google.com' target='_blank'>google</a>.</div><b>Teste 1</b><div><br></div><div>Para ver se tudo está funcionando, vamos fazer assim.</div><div><br></div><div>Para mais informações, consulte o&nbsp;<a href='http://www.google.com' target='_blank'>google</a>.</div><b>Teste 1</b><div><br></div><div>Para ver se tudo está funcionando, vamos fazer assim.</div><div><br></div><div>Para mais informações, consulte o&nbsp;<a href='http://www.google.com' target='_blank'>google</a>.</div><b>Teste 1</b><div><br></div><div>Para ver se tudo está funcionando, vamos fazer assim.</div><div><br></div><div>Para mais informações, consulte o&nbsp;<a href='http://www.google.com' target='_blank'>google</a>.</div><b>Teste 1</b><div><br></div><div>Para ver se tudo está funcionando, vamos fazer assim.</div><div><br></div><div>Para mais informações, consulte o&nbsp;<a href='http://www.google.com' target='_blank'>google</a>.</div><b>Teste 1</b><div><br></div><div>Para ver se tudo está funcionando, vamos fazer assim.</div><div><br></div><div>Para mais informações, consulte o&nbsp;<a href='http://www.google.com' target='_blank'>google</a>.</div><b>Teste 1</b><div><br></div><div>Para ver se tudo está funcionando, vamos fazer assim.</div><div><br></div><div>Para mais informações, consulte o&nbsp;<a href='http://www.google.com' target='_blank'>google</a>.</div><b>Teste 1</b><div><br></div><div>Para ver se tudo está funcionando, vamos fazer assim.</div><div><br></div><div>Para mais informações, consulte o&nbsp;<a href='http://www.google.com' target='_blank'>google</a>.</div><b>Teste 1</b><div><br></div><div>Para ver se tudo está funcionando, vamos fazer assim.</div><div><br></div><div>Para mais informações, consulte o&nbsp;<a href='http://www.google.com' target='_blank'>google</a>.</div><b>Teste 1</b><div><br></div><div>Para ver se tudo está funcionando, vamos fazer assim.</div><div><br></div><div>Para mais informações, consulte o&nbsp;<a href='http://www.google.com' target='_blank'>google</a>.</div><b>Teste 1</b><div><br></div><div>Para ver se tudo está funcionando, vamos fazer assim.</div><div><br></div><div>Para mais informações, consulte o&nbsp;<a href='http://www.google.com' target='_blank'>google</a>.</div><b>Teste 1</b><div><br></div><div>Para ver se tudo está funcionando, vamos fazer assim.</div><div><br></div><div>Para mais informações, consulte o&nbsp;<a href='http://www.google.com' target='_blank'>google</a>.</div><b>Teste 1</b><div><br></div><div>Para ver se tudo está funcionando, vamos fazer assim.</div><div><br></div><div>Para mais informações, consulte o&nbsp;<a href='http://www.google.com' target='_blank'>google</a>.</div><b>Teste 1</b><div><br></div><div>Para ver se tudo está funcionando, vamos fazer assim.</div><div><br></div><div>Para mais informações, consulte o&nbsp;<a href='http://www.google.com' target='_blank'>google</a>.</div><b>Teste 1</b><div><br></div><div>Para ver se tudo está funcionando, vamos fazer assim.</div><div><br></div><div>Para mais informações, consulte o&nbsp;<a href='http://www.google.com' target='_blank'>google</a>.</div><b>Teste 1</b><div><br></div><div>Para ver se tudo está funcionando, vamos fazer assim.</div><div><br></div><div>Para mais informações, consulte o&nbsp;<a href='http://www.google.com' target='_blank'>google</a>.</div><b>Teste 1</b><div><br></div><div>Para ver se tudo está funcionando, vamos fazer assim.</div><div><br></div><div>Para mais informações, consulte o&nbsp;<a href='http://www.google.com' target='_blank'>google</a>.</div><b>Teste 1</b><div><br></div><div>Para ver se tudo está funcionando, vamos fazer assim.</div><div><br></div><div>Para mais informações, consulte o&nbsp;<a href='http://www.google.com' target='_blank'>google</a>.</div><b>Teste 1</b><div><br></div><div>Para ver se tudo está funcionando, vamos fazer assim.</div><div><br></div><div>Para mais informações, consulte o&nbsp;<a href='http://www.google.com' target='_blank'>google</a>.</div><b>Teste 1</b><div><br></div><div>Para ver se tudo está funcionando, vamos fazer assim.</div><div><br></div><div>Para mais informações, consulte o&nbsp;<a href='http://www.google.com' target='_blank'>google</a>.</div><b>Teste 1</b><div><br></div><div>Para ver se tudo está funcionando, vamos fazer assim.</div><div><br></div><div>Para mais informações, consulte o&nbsp;<a href='http://www.google.com' target='_blank'>google</a>.</div></div>",
        "Active":true,
        "IsDBContent":true,
        "Author": "c08460"
    },
    {
        "Index": 2,
        "Id":"0000000002",
        "Parent" : "Chamado",
        "Category" : "Wiki",
        "Segment": "Social",
        "Title" : "Pedra do reino - excluir lançamento futuro fase de obra",
        "Description": "Como excluir lançamento futuro na conta, para prestação de acompanhamento de obra.",
        "Keys" : [],
        "Link" : ["http://www.caixa.gov.br"],
        "Hashtags" : ["#fies","#teste", "#aditamentofies"],
        "DateUpload": "08/07/2020",
        "Body" : "<p>Digitar guia de comando com os seguintes dados:<p>TD:11-6<br>CL:23-0<br>TP:29</p>",
        "Active":true,
        "IsDBContent":true,
        "Author": "c08460"
    },
    {
        "Index": 3,
        "Id":"0000000003",
        "Parent" : "wikiContents",
        "Category" : "Arquivo",
        "Segment": "Social",
        "Title": "Calendário Auxílio Emergencial",
        "Description": "Tabela mais recente completa, considerando novos aprovados.",
        "Keys" : [],
        "Link" : [],
        "Hashtags" : [],
        "DateUpload": "08/07/2020",
        "Body" : "<h1>teste deu certo! - 3</h1>",
        "Active":true,
        "IsDBContent":true,
        "Author": "c08460"
    },
    {
        "Index": 4,
        "Id":"0000000004",
        "Parent" : "wikiContents",
        "Category" : "Arquivo",
        "Segment": "Social",
        "Title": "Orientações sobre antecipação do FGTS - Saque Aniversário",
        "Description": "Orientações sobre as condições e como solicitar a antecipação do saque-aniversário do FGTS.",
        "Keys" : [],
        "Link" : [],
        "Hashtags" : ["#fies"],
        "DateUpload": "08/06/2020",
        "Body" : "<h1>teste deu certo! - 4</h1>",
        "Active":true,
        "IsDBContent":true,
        "Author": "c08460"
    },
    {
        "Index": 5,
        "Id":"0000000005",
        "Parent" : "wikiContents",
        "Category" : "Wiki",
        "Segment": "Social",
        "Title": "FIES - Encerramento",
        "Description": "Como solicitar encerramento do FIES e as opções de pagamento do saldo devedor.",
        "Link" : [],
        "Keys" : [],
        "Hashtags" : [],
        "DateUpload": "08/08/2020",
        "Body" : "<h1>teste deu certo! - 5</h1>",
        "Active":true,
        "IsDBContent":true,
        "Author": "c08460"
    },
    {
        "Index": 6,
        "Id":"0000000006",
        "Parent" : "Chamado",
        "Category" : "Wiki",
        "Segment": "Social",
        "Title" : "Alteração na pausa FIES - inadimplência em 20/03/2020",
        "Description": "Chamado sobre alteração nas condições de pausa do FIES pelo covid19, permitindo para inadimplência em 20/03/2020.",
        "Keys" : [],
        "Link" : ["http://www.caixa.gov.br"],
        "Hashtags" : ["#teste"],
        "DateUpload": "08/07/2020",
        "Body" : "<h1>teste deu certo! - 2</h1>",
        "Active":true,
        "IsDBContent":true,
        "Author": "c08460"
    },
    {
        "Index": 7,
        "Id":"0000000007",
        "Parent" : "Chamado",
        "Category" : "Wiki",
        "Segment": "Social",
        "Title" : "Alteração na pausa FIES - inadimplência em 20/03/2020",
        "Description": "Chamado sobre alteração nas condições de pausa do FIES pelo covid19, permitindo para inadimplência em 20/03/2020.",
        "Keys" : [],
        "Link" : ["http://www.caixa.gov.br"],
        "Hashtags" : ["#teste"],
        "DateUpload": "08/07/2020",
        "Body" : "<h1>teste deu certo! - 2</h1>",
        "Active":true,
        "IsDBContent":true,
        "Author": "c08460"
    },
    {
        "Index": 8,
        "Id":"0000000008",
        "Parent" : "Chamado",
        "Category" : "Wiki",
        "Segment": "Social",
        "Title" : "Alteração na pausa FIES - inadimplência em 20/03/2020",
        "Description": "Chamado sobre alteração nas condições de pausa do FIES pelo covid19, permitindo para inadimplência em 20/03/2020.",
        "Keys" : [],
        "Link" : ["http://www.caixa.gov.br"],
        "Hashtags" : ["#teste"],
        "DateUpload": "08/07/2020",
        "Body" : "<h1>teste deu certo! - 2</h1>",
        "Active":true,
        "IsDBContent":true,
        "Author": "c08460"
    },
    {
        "Index": 9,
        "Id":"0000000009",
        "Parent" : "Chamado",
        "Category" : "Wiki",
        "Segment": "Social",
        "Title" : "Alteração na pausa FIES - inadimplência em 20/03/2020",
        "Description": "Chamado sobre alteração nas condições de pausa do FIES pelo covid19, permitindo para inadimplência em 20/03/2020.",
        "Keys" : [],
        "Link" : ["http://www.caixa.gov.br"],
        "Hashtags" : ["#teste"],
        "DateUpload": "08/07/2020",
        "Body" : "<h1>teste deu certo! - 2</h1>",
        "Active":true,
        "IsDBContent":true,
        "Author": "c08460"
    },
    {
        "Index": 10,
        "Id":"0000000010",
        "Parent" : "Chamado",
        "Category" : "Wiki",
        "Segment": "Social",
        "Title" : "Alteração na pausa FIES - inadimplência em 20/03/2020",
        "Description": "Chamado sobre alteração nas condições de pausa do FIES por calamidade pública, permitindo para inadimplência em 20/03/2020.",
        "Keys" : [],
        "Link" : ["http://www.caixa.gov.br"],
        "Hashtags" : ["#teste"],
        "DateUpload": "08/07/2020",
        "Body" : "<h1>teste deu certo! - 2</h1>",
        "Active":true,
        "IsDBContent":true,
        "Author": "c08460"
    },
    {
        "Index": 11,
        "Id":"0000000011",
        "Parent" : "Chamado",
        "Category" : "Wiki",
        "Segment": "Social",
        "Title" : "Alteração na pausa FIES - inadimplência em 20/03/2020",
        "Description": "Chamado sobre alteração nas condições de pausa do FIES por calamidade pública, permitindo para inadimplência em 20/03/2020.",
        "Keys" : [],
        "Link" : ["http://www.caixa.gov.br"],
        "Hashtags" : ["#teste"],
        "DateUpload": "08/07/2020",
        "Body" : "<h1>teste deu certo! - 2</h1>",
        "Active":true,
        "IsDBContent":true,
        "Author": "c08460"
    },
    {
        "Index": 12,
        "Id":"0000000012",
        "Parent" : "Chamado",
        "Category" : "Wiki",
        "Segment": "Social",
        "Title" : "Alteração na pausa FIES - inadimplência em 20/03/2020",
        "Description": "Chamado sobre alteração nas condições de pausa do FIES por calamidade pública, permitindo para inadimplência em 20/03/2020.",
        "Keys" : [],
        "Link" : ["http://www.caixa.gov.br"],
        "Hashtags" : ["#teste"],
        "DateUpload": "08/07/2020",
        "Body" : "<h1>teste deu certo! - 2</h1>",
        "Active":true,
        "IsDBContent":true,
        "Author": "c08460"
    },
    {
        "Index": 13,
        "Id":"0000000013",
        "Parent" : "Chamado",
        "Category" : "Wiki",
        "Segment": "Social",
        "Title" : "Alteração na pausa FIES - inadimplência em 20/03/2020",
        "Description": "Chamado sobre alteração nas condições de pausa do FIES por calamidade pública, permitindo para inadimplência em 20/03/2020.",
        "Keys" : [],
        "Link" : ["http://www.caixa.gov.br"],
        "Hashtags" : ["#teste"],
        "DateUpload": "08/07/2020",
        "Body" : "<h1>teste deu certo! - 2</h1>",
        "Active":true,
        "IsDBContent":true,
        "Author": "c08460"
    },
    {
        "Index": 14,
        "Id":"0000000014",
        "Parent" : "Chamado",
        "Category" : "Wiki",
        "Segment": "PJ",
        "Title" : "Alteração na pausa FIES - inadimplência em 20/03/2020",
        "Description": "Chamado sobre alteração nas condições de pausa do FIES por calamidade pública, permitindo para inadimplência em 20/03/2020.",
        "Keys" : [],
        "Link" : ["http://www.caixa.gov.br"],
        "Hashtags" : ["#teste"],
        "DateUpload": "08/07/2020",
        "Body" : "<h1>teste deu certo! - 2</h1>",
        "Active":true,
        "IsDBContent":true,
        "Author": "c08460"
    },
    {
        "Index": 15,
        "Id":"0000000015",
        "Parent" : "Chamado",
        "Category" : "Wiki",
        "Segment": "PF",
        "Title" : "Alteração na pausa FIES - inadimplência em 20/03/2020",
        "Description": "Chamado sobre alteração nas condições de pausa do FIES por calamidade pública, permitindo para inadimplência em 20/03/2020.",
        "Keys" : [],
        "Link" : ["http://www.caixa.gov.br"],
        "Hashtags" : ["#teste"],
        "DateUpload": "08/07/2020",
        "Body" : "<h1>teste deu certo! - 2</h1>",
        "Active":true,
        "IsDBContent":true,
        "Author": "c08460"
    },
    {
        "Index": 16,
        "Id":"0000000016",
        "Parent" : "Chamado",
        "Category" : "Wiki",
        "Segment": "Habitação",
        "Title" : "Pausa financiamento habitacional - covid19",
        "Description": "Como identificar até que mês um financiamento está pausado pela ação COVID19.",
        "Keys" : [],
        "Link" : ["ciweb.extranet.caixa/caixa"],
        "Hashtags" : ["#pausacovid", "#pausaemergencial", "#pausafinanciamento"],
        "DateUpload": "22/08/2020",
        "Body" : "<p>Para saber até que mês um financiamento habitacional está pausado, acesse a tela CPE e identifique o TP 240. Ao clicar no número do pedido, marque na tela seguinte e caixa \"Condições de Financiamento\", e pressione o botão \"Consultar \". O contrato estará pausado até o mês que constar no campo \"Mês Interrupção\".</p><p>Atenção: Na tela CPE vetifique o código do TP 240. O Código 01 significa inclusão do pedido de pausa; o 03 significa alteração e 02 significa exclusão.</p>",
        "Active":true,
        "IsDBContent":true,
        "Author": "c08460"
    }
];
